name: Continuous Deployment

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build and publish the container image
    uses: mozilla/remote-settings/.github/workflows/ingestion-job-publish.yaml@main
    with:
      # Publish `main` branch to `nonprod` and tags to `prod`
      realm: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && 'prod' || 'nonprod' }}
      # Build but do not publish the container on pull-requests
      publish: ${{ github.event_name != 'pull_request' }}
